import { rm } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Bundle the workspace into the installable skill directory.
 *
 * `skills add` clones a repo and *copies files* — it does not run a build. So
 * everything the skill needs at runtime has to be committed: the bundled CLI
 * and the built UI both live in `skills/ledger-memory/` as tracked artifacts,
 * regenerated by this script rather than by whoever installs it.
 *
 * SKILL.md is deliberately not generated. It is prose, hand-written, and the
 * most important file in the directory.
 */

const ROOT = join(import.meta.dir, '..')
const SKILL = join(ROOT, 'skills', 'ledger-memory')

const step = (message: string): void => {
  process.stdout.write(`  ${message}\n`)
}

// 1. The CLI, as a single file. bun:sqlite stays a runtime builtin.
await rm(join(SKILL, 'cli.js'), { force: true })
const built = await Bun.build({
  entrypoints: [join(ROOT, 'packages', 'cli', 'src', 'bin.ts')],
  outdir: SKILL,
  target: 'bun',
  format: 'esm',
  naming: 'cli.js',
  minify: false, // A skill people can read is a skill people can trust.
})

if (!built.success) {
  for (const log of built.logs) console.error(log)
  process.exit(1)
}

const cli = Bun.file(join(SKILL, 'cli.js'))
step(`cli.js        ${(cli.size / 1024).toFixed(0)} KB`)

// 2. The UI, copied from the Vite build.
const uiSource = join(ROOT, 'packages', 'ui', 'dist')
if (!(await Bun.file(join(uiSource, 'index.html')).exists())) {
  console.error('  ✕ packages/ui/dist is missing — run `bun run build` first')
  process.exit(1)
}

const uiTarget = join(SKILL, 'ui')
await rm(uiTarget, { recursive: true, force: true })

const copied = await Bun.$`cp -R ${uiSource} ${uiTarget}`.quiet().nothrow()
if (copied.exitCode !== 0) {
  console.error(`  ✕ could not copy the UI: ${copied.stderr.toString()}`)
  process.exit(1)
}

const uiSize = await Bun.$`du -sk ${uiTarget}`.quiet().text()
step(`ui/           ${uiSize.trim().split('\t')[0]} KB`)

// 3. SKILL.md is source, not output — but the bundle is useless without it.
if (!(await Bun.file(join(SKILL, 'SKILL.md')).exists())) {
  console.error('  ✕ skills/ledger-memory/SKILL.md is missing')
  process.exit(1)
}
step('SKILL.md      (source, not rebuilt)')

process.stdout.write(
  `\n  Skill ready at skills/ledger-memory — commit it, or it installs empty.\n\n`,
)
